const crypto = require("crypto");
const { google } = require("googleapis");

const ROOT_FOLDER_ID = process.env.GDRIVE_FOLDER_ID || "1fGNsPdZqi4rxEOeFmL-yruHR6PNglC7_";
const MAX_FILES = Number(process.env.MAX_FILES || 5);
const MAX_BYTES = Number(process.env.MAX_BYTES || 25 * 1024 * 1024);
const BODY_LIMIT = Number(process.env.BODY_LIMIT_BYTES || 35 * 1024 * 1024);
const CORS_ORIGINS = new Set([
  "https://bennett-maxwell.github.io",
  "https://mvhs-reunion-2026.vercel.app",
  "http://localhost:3000",
  "http://localhost:3001",
]);

function setCors(req, res) {
  const origin = req.headers.origin || "";
  if (CORS_ORIGINS.has(origin)) {
    res.setHeader("Access-Control-Allow-Origin", origin);
    res.setHeader("Vary", "Origin");
  }
  res.setHeader("Access-Control-Allow-Methods", "POST,OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
}

function json(res, status, body) {
  res.statusCode = status;
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.end(JSON.stringify(body));
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let total = 0;
    const chunks = [];
    req.on("data", (chunk) => {
      total += chunk.length;
      if (total > BODY_LIMIT) {
        reject(new Error("Upload is too large for this endpoint."));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

function driveClient() {
  const required = ["GDRIVE_CLIENT_ID", "GDRIVE_CLIENT_SECRET", "GDRIVE_REFRESH_TOKEN"];
  const missing = required.filter((key) => !process.env[key]);
  if (missing.length) {
    throw new Error(`Server is missing Drive credentials: ${missing.join(", ")}`);
  }
  const auth = new google.auth.OAuth2(
    process.env.GDRIVE_CLIENT_ID,
    process.env.GDRIVE_CLIENT_SECRET
  );
  auth.setCredentials({ refresh_token: process.env.GDRIVE_REFRESH_TOKEN });
  return google.drive({ version: "v3", auth });
}

function safeName(value) {
  return String(value || "")
    .replace(/[\\/:*?"<>|#%{}^~[\]`]+/g, "_")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 80) || "contributor";
}

function contributorLabel(contributor) {
  const name = `${contributor.first || ""} ${contributor.last || ""}`.trim();
  return safeName(name || contributor.phone || contributor.email || "contributor");
}

function nowStamp() {
  return new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19) + "Z";
}

async function createFolder(drive, name, parentId) {
  const created = await drive.files.create({
    requestBody: {
      name,
      mimeType: "application/vnd.google-apps.folder",
      parents: [parentId],
    },
    fields: "id,webViewLink",
    supportsAllDrives: true,
  });
  return created.data;
}

async function uploadBuffer(drive, { name, mimeType, buffer, parentId, description }) {
  const { Readable } = require("stream");
  const created = await drive.files.create({
    requestBody: {
      name,
      parents: [parentId],
      description,
    },
    media: {
      mimeType,
      body: Readable.from(buffer),
    },
    fields: "id,name,webViewLink,size,mimeType",
    supportsAllDrives: true,
  });
  return created.data;
}

async function appendSubmissionLog(drive, line) {
  const q = [
    `'${ROOT_FOLDER_ID}' in parents`,
    "name = 'submissions-vercel.jsonl'",
    "trashed = false",
  ].join(" and ");
  const existing = await drive.files.list({
    q,
    fields: "files(id,name)",
    supportsAllDrives: true,
    includeItemsFromAllDrives: true,
  });
  if (!existing.data.files || existing.data.files.length === 0) {
    await uploadBuffer(drive, {
      name: "submissions-vercel.jsonl",
      mimeType: "text/plain",
      buffer: Buffer.from(line + "\n", "utf8"),
      parentId: ROOT_FOLDER_ID,
      description: "MVHS 2011 upload log generated by Vercel endpoint.",
    });
    return;
  }

  const fileId = existing.data.files[0].id;
  const current = await drive.files.get(
    { fileId, alt: "media", supportsAllDrives: true },
    { responseType: "arraybuffer" }
  );
  const next = Buffer.concat([
    Buffer.from(current.data || ""),
    Buffer.from(line + "\n", "utf8"),
  ]);
  const { Readable } = require("stream");
  await drive.files.update({
    fileId,
    media: { mimeType: "text/plain", body: Readable.from(next) },
    supportsAllDrives: true,
  });
}

function validate(payload) {
  if (!payload || typeof payload !== "object") return "Missing upload payload.";
  const contributor = payload.contributor || {};
  if (!contributor.first && !contributor.last && !contributor.phone) {
    return "Please add a name or phone number.";
  }
  if (!payload.consent) return "Consent is required.";
  if (!Array.isArray(payload.photos) || payload.photos.length === 0) {
    return "Please add at least one photo.";
  }
  if (payload.photos.length > MAX_FILES) return `Please send no more than ${MAX_FILES} photos.`;
  return null;
}

module.exports = async function handler(req, res) {
  setCors(req, res);
  if (req.method === "OPTIONS") {
    res.statusCode = 204;
    return res.end();
  }
  if (req.method !== "POST") return json(res, 405, { ok: false, error: "Use POST." });

  try {
    const raw = await readBody(req);
    const payload = JSON.parse(raw);
    const problem = validate(payload);
    if (problem) return json(res, 400, { ok: false, error: problem });

    const drive = driveClient();
    const contributor = payload.contributor || {};
    const folderName = `${contributorLabel(contributor)} ${nowStamp()}`;
    const folder = await createFolder(drive, folderName, ROOT_FOLDER_ID);
    const stored = [];

    for (const [index, photo] of payload.photos.entries()) {
      if (!photo || !photo.bytesBase64) {
        return json(res, 400, { ok: false, error: "A photo was missing its bytes." });
      }
      const buffer = Buffer.from(String(photo.bytesBase64), "base64");
      if (buffer.length > MAX_BYTES) {
        return json(res, 413, { ok: false, error: `${photo.filename || "A photo"} is too large.` });
      }
      const serverHash = crypto.createHash("sha256").update(buffer).digest("hex");
      const clientHash = String(photo.sha256 || "").toLowerCase();
      if (clientHash && clientHash !== serverHash) {
        return json(res, 400, { ok: false, error: `${photo.filename || "Photo"} failed integrity check.` });
      }
      const uploaded = await uploadBuffer(drive, {
        name: safeName(photo.filename || `photo-${index + 1}.jpg`),
        mimeType: photo.type || "application/octet-stream",
        buffer,
        parentId: folder.id,
        description: `MVHS2011 sha256=${serverHash} integrity=OK`,
      });
      stored.push({
        filename: uploaded.name,
        fileId: uploaded.id,
        url: uploaded.webViewLink,
        serverHash,
        bytes: buffer.length,
      });
    }

    await appendSubmissionLog(drive, JSON.stringify({
      at: new Date().toISOString(),
      project: payload.project || "mvhs-reunion",
      contributor,
      consent: Boolean(payload.consent),
      folderId: folder.id,
      folderUrl: folder.webViewLink,
      photos: stored,
    }));

    return json(res, 200, { ok: true, stored: stored.length, folder: folder.webViewLink, photos: stored });
  } catch (error) {
    return json(res, 500, { ok: false, error: error.message || String(error) });
  }
};
